services:
  ########################################
  # ZOOKEEPER
  ########################################
  zookeeper:
    image: bitnami/zookeeper:3.8.1
    container_name: zookeeper
    environment:
      - ZOO_ENABLE_AUTH=yes
    ports:
      - "2181:2181"

  ########################################
  # KAFKA
  ########################################
  kafka:
    image: bitnami/kafka:3.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
    ports:
      - "9092:9092"

  ########################################
  # MONGODB
  ########################################
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"

  ########################################
  # NIFI
  ########################################
  nifi:
    image: apache/nifi:1.19.1
    container_name: nifi
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_JVM_HEAP_INIT=2G
      - NIFI_JVM_HEAP_MAX=4G
    ports:
      - "8080:8080"

  ########################################
  # SPARK MASTER
  ########################################
  spark-master:
    image: bitnami/spark:3.3.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MEMORY=2G
    ports:
      - "8081:8080"  # Spark master web UI
      - "7077:7077"  # Spark master RPC port

  ########################################
  # SPARK WORKER
  ########################################
  spark-worker:
    image: bitnami/spark:3.3.2
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
    ports:
      - "8082:8080"

  ########################################
  # BACKEND
  ########################################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - kafka
      - mongodb
      - nifi
      - spark-master
      - spark-worker
    environment:
      - PORT=3000
      - NIFI_BASE_URL=http://nifi:8080/nifi-api
      - KAFKA_BROKER=kafka:9092
      - SPARK_MASTER=spark://spark-master:7077
      - MONGODB_URL=mongodb://mongodb:27017/ml-pipelines
    ports:
      - "3000:3000"

  ########################################
  # FRONTEND
  ########################################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"

  ########################################
  # PROMETHEUS
  ########################################
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

########################################
  # cADVISOR (Official Image)
  ########################################
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8085:8080"  # Host port 8085, container port 8080

volumes:
  mongo_data:

