global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'custom_exporter'
    static_configs:
      - targets: ['custom-exporter:9100']
